#!/bin/bash

test="${1}"
case "${test}" in
  test/pipe)
    ${test} pull &
    pid=$!
    trap "kill ${pid} && exit" SIGTERM SIGINT
    sleep .5
    ${test} push
    ;;

  test/radio)
    ${test} node0 &
    pid=$!
    trap "kill ${pid} && exit" SIGTERM SIGINT
    sleep 1
    ${test} node1
    ;;

  test/topic)
    ${test} server &
    pid=$!
    trap "kill ${pid} && exit" SIGTERM SIGINT
    sleep .5
    for i in {1..10}; do
      ${test} client
      sleep .01
    done
    kill ${pid}
    ;;

  test/survey)
    for i in {1..10}; do
      ${test} client &
      pid=$!
      trap "kill ${pid} && exit" SIGTERM SIGINT
    done
    ${test} server
    ;;

  *)
    ${test}
    ;;
esac

rc=$?
wait
exit $?

