#!/bin/bash

test="${1}"
case "${test}" in
  test/pipe)
    ${test} pull &
    sleep .5
    ${test} push
    ;;

  test/radio)
    ${test} node0 &
    sleep .5
    ${test} node1
    ;;

  *)
    ${test}
    ;;
esac

rc=$?
wait
exit $?

